---
apiVersion: v1
kind: Namespace
metadata:
  name:  colour-picker
---

apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: colour-picker
  name: deploy-colour-picker
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: colour-picker
  replicas: 3
  template:
    metadata:
      labels:
        app.kubernetes.io/name: colour-picker
    spec:
      containers:
      - name: colour-picker
        image: samedwardsweg/colour-picker:1.2
        imagePullPolicy: Always
        ports:
        - containerPort: 80
---

kind: Service
apiVersion: v1
metadata:
  namespace: colour-picker
  name:  service-colour-picker
spec:
  ports:
  - port:  80
    targetPort:  80
    protocol: TCP
    name: http
  type: LoadBalancer
  selector:
    app.kubernetes.io/name: colour-picker
---

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  namespace: colour-picker
  name: ingress-colour-picker
  annotations:
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: ip
spec:
  ingressClassName: alb
  rules:
    - http:
        paths:
        - path: /
          pathType: Prefix
          backend:
            service:
              name: service-colour-picker
              port:
                number: 80